import { BaseConfig } from '../types/configTypes';
import { DEFAULT_FONT_FAMILY } from './defaultFontFamily';
import {
	NEUTRAL_DESELECTED_COLOR,
	NEUTRAL_HIGHLIGHT_COLOR,
	NEUTRAL_SERIES_COLORS,
} from './shippedNeutralDefaults';

const baseConfig: BaseConfig = {
	layout: {
		name: 'wp-block-prc-block-chart-builder-controller',
		parentClass: undefined,
		type: 'bar',
		orientation: 'vertical',
		width: 640,
		height: 400,
		padding: { top: 0, bottom: 0, left: 0, right: 0 },
		overflowX: 'responsive',
		horizontalRules: true,
		mobileBreakpoint: 480,
	},
	metadata: {
		active: false,
		title: '',
		subtitle: '',
		note: '',
		source: '',
		tag: '',
		alt: '',
	},
	colors: [...NEUTRAL_SERIES_COLORS],
	plotBands: {
		active: false,
		allowDrag: false,
		allowResize: false,
		dimension: 'x',
		bands: [],
	},
	independentAxis: {
		active: true,
		label: '',
		scale: 'linear',
		dateFormat: '%-m/%Y',
		domain: [0, 100],
		domainPadding: 20,
		showZero: false,
		padding: 60,
		tickAngle: 0,
		tickCount: 5,
		tickValues: undefined,
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: false,
		abbreviateTicksDecimals: 0,
		tickUnit: '', //'%', '$', '€', '£', '¥'
		tickUnitPosition: 'end',
		customTickFormat: null, // function(d) { return d; },
		tickLabels: {
			fontSize: 12,
			padding: 0,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'middle',
			verticalAnchor: 'start',
			fill: '#2a2a2a',
			fontFamily: DEFAULT_FONT_FAMILY,
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: '#2a2a2a',
			padding: 15,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: DEFAULT_FONT_FAMILY,
			maxWidth: 200,
		},
		axis: {
			stroke: '#756f6a',
			strokeWidth: 1,
		},
		ticks: {
			stroke: '#756f6a',
			size: 5,
			strokeWidth: 0,
		},
		grid: {
			stroke: '#dadbdb',
			strokeOpacity: 1,
			strokeWidth: 2,
			strokeDasharray: '.3,6',
		},
	},
	dependentAxis: {
		active: false,
		label: '',
		scale: 'linear',
		padding: 100,
		domain: [0, 200],
		domainPadding: 20,
		// True matches how the pre-flag library always rendered value scales;
		// charts saved without a `nice` key backfill this in get-config.
		nice: true,
		showZero: true,
		tickCount: 10,
		tickValues: undefined,
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: true,
		abbreviateTicksDecimals: 0,
		tickUnit: '', //'%', '$', '€', '£', '¥'
		tickUnitPosition: 'end',
		customTickFormat: null, // function(d) { return d; },
		tickLabels: {
			fontSize: 12,
			fill: '#2a2a2a',
			padding: 15,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: DEFAULT_FONT_FAMILY,
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: '#2a2a2a',
			padding: 50,
			angle: 270,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: DEFAULT_FONT_FAMILY,
			maxWidth: 50,
		},
		ticks: {
			stroke: '#756f6a',
			size: 5,
			strokeWidth: 0,
		},
		axis: {
			stroke: '#756f6a',
			strokeWidth: 1,
		},
		grid: {
			stroke: '#dadbdb',
			strokeOpacity: 1,
			strokeWidth: 2,
			strokeDasharray: '.3,6',
		},
	},
	dataRender: {
		x: 'x',
		y: 'y',
		x2: null,
		y2: null,
		sortKey: 'y',
		sortOrder: 'ascending',
		categories: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
		xScale: 'linear',
		yScale: 'linear',
		xFormat: null,
		yFormat: null,
		numberFormat: 'en-US',
		isHighlightedColor: NEUTRAL_HIGHLIGHT_COLOR,
		highlightColor: NEUTRAL_HIGHLIGHT_COLOR,
		deselectedColor: NEUTRAL_DESELECTED_COLOR,
		deselectedOpacity: 1,
		highlightedCategories: [],
		rowFilter: { column: 'x', exclude: [] },
		mapScale: 'threshold',
		mapScaleDomain: [10, 20, 30, 40, 50],
		mapStyle: 'choropleth',
		groupBreaksActive: false,
		groupBreaksCategory: 'Continent',
		groupBreaksCategoryValues: [
			'Africa',
			'Asia',
			'Europe',
			'North America',
			'South America',
			'Oceania',
		],
		groupBreaks: {
			breakStyles: {
				variation: 'empty',
				stroke: '#A4A4A4',
				strokeWidth: 1.4,
				height: 30,
				strokeDasharray: 'none',
			},
			labelStyles: {
				fill: 'black',
				fontStyle: 'normal',
			},
		},
	},
	animate: {
		active: false,
		animationWhitelist: [],
		duration: 2000, //time in ms
	},
	// Additive PRC-17 config — consumed by the `animated/` primitives via
	// `useAnimationConfig`. DISABLED by default (slice 3c): animation is
	// opt-in per chart via the Inspector's Animation panel
	// (`config.animation.enabled`). Reduced-motion users and the editor
	// always render instantly regardless of this flag (handled in the
	// hook). Authors retune `duration`/`easing`/`initial`/`update` through
	// the same panel; callers can also flip it via `setConfig` (slice 4+).
	animation: {
		enabled: false,
		duration: 400,
	},
	events: {},
	tooltip: {
		active: false,
		mode: 'point',
		headerActive: true,
		headerValue: 'independentValue',
		format: '{{row}}: {{value}}',
		template: null,
		offsetX: 10,
		offsetY: 10,
		abbreviateValue: false,
		absoluteValue: false,
		toFixedDecimal: 0,
		truncateDecimal: false,
		minDisplayValue: null,
		toLocaleString: true,
		customFormat: null, // function(d) { return d; },
		rlsFormat: false,
		dateFormat: '%-m/%Y',
		caretPosition: 'bottom',
		deemphasizeSiblings: false,
		deemphasizeOpacity: 0.5,
		emphasizeStrokeActive: false,
		emphasizeStrokeColor: 'black',
		emphasizeStrokeWidth: 1,
		style: {
			minWidth: 50,
			maxWidth: 200,
			maxHeight: 100,
			minHeight: 20,
			width: 'auto',
			height: 'auto',
			fontSize: '13px',
			fontFamily: DEFAULT_FONT_FAMILY,
			background: 'white',
			border: '1px solid #CBCBCB',
			padding: '10px',
			borderRadius: '0px',
			color: 'black',
		},
	},
	legend: {
		active: false,
		variation: 'grouped',
		orientation: 'row',
		title: '',
		alignment: 'center',
		offsetX: 0,
		offsetY: 0,
		markerStyle: 'rect',
		markerFill: 'solid',
		borderStroke: 'black',
		fill: 'white',
		fontWeight: 'normal',
		fontFamily: DEFAULT_FONT_FAMILY,
		categories: [],
		labelDelimiter: 'to',
		labelLower: 'Less than ',
		labelUpper: 'More than ',
		fontSize: 12,
		margin: {
			top: 0,
			right: 5,
			bottom: 0,
			left: 0,
		},
		customLabels: {},
		bubbleLegend: {
			fill: 'category',
			stroke: 'transparent',
			refValues: [],
			layout: 'stacked',
			labelPosition: 'outside',
		},
	},
	bar: {
		hasRectStroke: false,
		rectStrokeColor: 'white',
		rectStrokeWidth: 1,
		barGroupPadding: 0.2,
		barPadding: 0.2,
	},
	beeSwarm: {
		layoutMode: 'dodge',
		groupBy: null,
		forceStrength: 0.1,
		swarmSpread: 24,
	},
	line: {
		interpolation: 'curveLinear',
		strokeDasharray: '1',
		strokeWidth: 3,
		showPoints: true,
		showFirstLastPointsOnly: false,
		showArea: false,
		areaFillOpacity: 0.4,
	},
	dotPlot: {
		connectPoints: true,
		connectingLine: {
			stroke: '#e6e7e8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
	},
	errorBars: {
		enabled: false,
		defaultStyles: {
			stroke: '#e6e7e8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
		categories: {},
		customStyles: {},
	},
	explodedBar: {
		columnGap: 16,
	},
	pie: {
		showCategoryLabels: true,
		hasPathStroke: true,
		pathStrokeColor: 'white',
		pathStrokeWidth: 1,
		groupGapAngle: 10, // Explode offset in pixels
		showGroupArcs: false,
		groupArcStyle: {
			stroke: '#666666',
			strokeWidth: 1,
			strokeDasharray: '4,4',
		},
	},
	nodes: {
		pointSize: 3,
		pointFill: 'inherit',
		pointFillOpacity: 1,
		pointStrokeWidth: 1,
		pointStroke: 'inherit',
		pointCustomSize: null, // function(d) { return d; },
		sizeCategory: null,
		sizeScale: 'sqrt',
		minPointSize: 4,
		maxPointSize: 24,
	},
	labels: {
		active: false,
		showFirstLastPointsOnly: false,
		firstLastLabelLayout: 'default',
		color: 'inherit',
		fontWeight: 200,
		fontSize: 12,
		fontFamily: DEFAULT_FONT_FAMILY,
		labelPositionBar: 'inside',
		labelCutoff: 0,
		minDisplayValue: null,
		labelPositionDX: -25,
		labelPositionDY: 0,
		pieLabelRadius: 60,
		abbreviateValue: false,
		absoluteValue: false,
		toLocaleString: true,
		truncateDecimal: false,
		toFixedDecimal: 0,
		labelUnit: '', //'%', '$', '€', '£', '¥'
		labelUnitPosition: 'end',
		textAnchor: 'middle',
		customLabelFormat: null, // function({datum}) { return datum; },
		autoDeclutter: false,
		declutterPadding: 4,
		declutterLeaderLines: false,
		textOutline: false,
	},
	shapes: {
		customStyles: {},
		segmentStyles: {},
	},
	voronoi: {
		active: false,
		fill: '#756a7e',
		stroke: '#ccc',
		strokeWidth: 1,
		strokeOpacity: 0.5,
	},
	regression: {
		active: false,
		type: 'linear',
		stroke: '#2a2a2a',
		strokeWidth: 2,
		strokeDasharray: '',
		perGroupBreak: false,
		groupBreakStyles: {},
	},
	divergingBar: {
		positiveCategories: ['y', 'y1'],
		negativeCategories: ['y2', 'y3'],
		netPositiveCategory: 'y4',
		netNegativeCategory: 'y5',
		percentOfInnerWidth: 0.7,
		neutralBar: {
			active: false,
			offsetX: -20,
			separator: true,
			separatorOffsetX: -1,
			category: 'y4',
		},
	},
	diffColumn: {
		active: false,
		category: '',
		columnHeader: 'Diff',
		customLabels: {},
		dx: 0,
		dy: 0,
		style: {
			rectStrokeWidth: 0,
			rectStrokeColor: 'white',
			rectFill: 'none',
			fill: '#2a2a2a',
			headerFill: '#2a2a2a',
			textOutline: false,
			headerTextOutline: false,
			fontWeight: 'normal',
			fontStyle: 'normal',
			headerFontWeight: 'normal',
			headerFontStyle: 'normal',
			headerFontFamily: '',
			fontSize: '10px',
			fontFamily: DEFAULT_FONT_FAMILY,
			headerFontSize: '12px',
			marginLeft: 10,
			width: 30,
			heightOffset: 0,
		},
	},
	netValues: {
		active: false,
		positive: {
			active: true,
			category: '',
			color: 'black',
			fontWeight: 400,
			fontSize: 12,
			fontFamily: '',
			textAnchor: 'middle',
			labelPositionDX: 0,
			labelPositionDY: 0,
			abbreviateValue: false,
			absoluteValue: false,
			truncateDecimal: false,
			toFixedDecimal: 0,
			toLocaleString: false,
			labelUnit: '',
			labelUnitPosition: 'end',
			margin: 5,
		},
		negative: {
			active: false,
			category: '',
			color: 'black',
			fontWeight: 400,
			fontSize: 12,
			fontFamily: '',
			textAnchor: 'middle',
			labelPositionDX: 0,
			labelPositionDY: 0,
			abbreviateValue: false,
			absoluteValue: false,
			truncateDecimal: false,
			toFixedDecimal: 0,
			toLocaleString: false,
			labelUnit: '',
			labelUnitPosition: 'end',
			margin: 5,
		},
	},
	map: {
		ignoreSmallStateLabels: false,
		ignoredLabels: [],
		abbreviateLabels: true,
		blockRectSize: 44,
		pathBackgroundFill: '#f7f7f7',
		pathStroke: '#dadbdb',
		pathStrokeWidth: 0.5,
		showCountyBoundaries: false,
		showStateBoundaries: true,
		zoomActive: false,
		// Projection controls - defaults result in standard world view
		projectionPreset: 'default',
		topologyRegion: 'default', // Which regional topology file to load (independent of projection)
		centerLongitude: 0,
		centerLatitude: 0,
		rotateLambda: 0,
		rotatePhi: 0,
		rotateGamma: 0,
		customScale: 1,
		bubble: {
			minRadius: 4,
			maxRadius: 24,
			opacity: 0.7,
			stroke: '#ffffff',
			strokeWidth: 1,
		},
		geoPoints: {
			latitudeColumn: 'Latitude',
			longitudeColumn: 'Longitude',
			labelColumn: 'x',
			sizeCategory: undefined,
			fixedRadius: undefined,
		},
		globe: {
			sphereFill: 'light-dark(#eef3f6, #1b2a33)',
			showGraticule: true,
			graticuleStroke: 'light-dark(#cdd8de, #2f4250)',
			autoSpin: false,
			spinSpeed: 0.2,
			dragToRotate: true,
			showPlayPause: true,
			playPausePosition: 'bottom-right',
			topology: 'full',
		},
	},
	custom: {
		isCustomChart: false,
		attributes: {
			chartType: null,
		},
	},
	annotations: {
		active: false,
		items: [],
	},
	drawings: {
		active: false,
		items: [],
	},
	treemap: {
		tile: 'squarify',
		rectStroke: '#ffffff',
		rectStrokeWidth: 2,
		labelMinArea: 1600,
		paddingInner: 2,
		paddingOuter: 4,
		scaleOpacity: false,
		opacityRange: [0.4, 1],
		borderRadius: 0,
		showValues: false,
	},
	sankey: {
		nodeAlign: 'justify',
		nodeWidth: 12,
		nodePadding: 10,
		linkOpacity: 0.5,
		nodeRadius: 0,
		sourceKey: 'x',
		targetKey: 'target',
		valueKey: 'value',
	},
	smallMultiples: {
		panelType: 'line',
		columns: 3,
		panelHeight: 184,
		minPanelWidth: 120,
		sharedScale: true,
		axisTreatment: 'minimal',
		emphasisMode: 'own-series',
		ghost: {
			stroke: '#E6E7E8',
			strokeWidth: 1.5,
			opacity: 1,
		},
		panelGap: {
			x: 24,
			y: 32,
		},
		panelTitle: {
			active: true,
			fontSize: 13,
			fontWeight: 700,
			fontFamily: 'var:preset|font-family|sans-serif',
			fill: '#2a2a2a',
			padding: 8,
			textAlign: 'center',
		},
	},
	waffle: {
		cellShape: 'square',
		cellGap: 0.1,
		cellRadius: 3,
		emptyFill: '#E6E7E8',
		columns: 10,
		rows: 10,
		max: null,
		cellSize: 14,
		cellSizeMode: 'clamp',
		displayMode: 'whole',
	},
	heatMapTable: {
		cellGap: 0,
		cellRadius: 0,
		showValues: true,
		emptyFill: '#F5F5F5',
		rowLabelWidth: 0,
		columnHeaderHeight: 48,
		minCellWidth: 40,
		minCellHeight: 28,
	},
};

export default baseConfig;
